### ISSUE TITLE
Cannot pass CI test in python3.9 because of MDA

### ISSUE THREAD

**Issue by RlyehAD** [MolSSI/mmic_optim_gmx#2]
The code in my latest PR has problem passing the test on MacOS latest, Python 3.9. And it is not related to the code itself but the installation of the necessary package MDAnalysis. This package is installed using `requirememts.txt` in `mmic_mda` component. When installing this dependency, the following error is reported:

  

>   clang -bundle -undefined dynamic_lookup -Wl,-rpath,/usr/local/miniconda/envs/test/lib -L/usr/local/miniconda/envs/test/lib -Wl,-rpath,/usr/local/miniconda/envs/test/lib -L/usr/local/miniconda/envs/test/lib -arch x86_64 build/temp.macosx-10.9-x86_64-3.9/MDAnalysis/analysis/encore/clustering/affinityprop.o build/temp.macosx-10.9-x86_64-3.9/MDAnalysis/analysis/encore/clustering/src/ap.o -lm -o build/lib.macosx-10.9-x86_64-3.9/MDAnalysis/analysis/encore/clustering/affinityprop.cpython-39-darwin.so
>     building 'MDAnalysis.analysis.encore.dimensionality_reduction.stochasticproxembed' extension
>     creating build/temp.macosx-10.9-x86_64-3.9/MDAnalysis/analysis/encore/dimensionality_reduction
>     creating build/temp.macosx-10.9-x86_64-3.9/MDAnalysis/analysis/encore/dimensionality_reduction/src
>     clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /usr/local/miniconda/envs/test/include -fPIC -O2 -isystem /usr/local/miniconda/envs/test/include -I/usr/local/miniconda/envs/test/lib/python3.9/site-packages/numpy/core/include -IMDAnalysis/analysis/encore/dimensionality_reduction/include -I/usr/local/miniconda/envs/test/include/python3.9 -c MDAnalysis/analysis/encore/dimensionality_reduction/src/spe.c -o build/temp.macosx-10.9-x86_64-3.9/MDAnalysis/analysis/encore/dimensionality_reduction/src/spe.o -std=c99 -ffast-math -O3 -funroll-loops -fsigned-zeros
>     MDAnalysis/analysis/encore/dimensionality_reduction/src/spe.c:197:22: error: implicit declaration of function 'getpid' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
>         srand(time(NULL)+getpid()*getpid());
>                          ^
>     1 error generated.
>     error: command '/usr/bin/clang' failed with exit code 1
>     ----------------------------------------
> ERROR: Command errored out with exit status 1: /usr/local/miniconda/envs/test/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/pip-install-cggreigt/mdanalysis_5399d67cd3a44e87ac6fee0a4476785e/setup.py'"'"'; __file__='"'"'/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/pip-install-cggreigt/mdanalysis_5399d67cd3a44e87ac6fee0a4476785e/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/pip-record-48xxc07v/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/miniconda/envs/test/include/python3.9/MDAnalysis Check the logs for full command output.
> Error: Process completed with exit code 1.

The whole error message is available [here](https://github.com/MolSSI/mmic_optim_gmx/pull/1/checks?check_run_id=2495181080). It seems like a compiler conflict.

**Comment by andrew-abimansour** [comment]
Did you try installing MDA from conda?

**Comment by RlyehAD** [comment]
Just tried on a 2017 Mac with macOS 11.2.3. It can be installed from the channel of conda-forge successfully.

**Comment by RlyehAD** [comment]
It can also be correctly imported by conda python.

**Comment by andrew-abimansour** [comment]
GHA CI [run](https://github.com/MolSSI/mmic_optim_gmx/actions/runs/807959089) on Mac OS X (python 3.9) failed as well in compiling MDA modules. 

I switched to a conda-forge installation as shown in the [run](https://github.com/MolSSI/mmic_optim_gmx/actions/runs/808231606) here, and the problem is solved.

**Comment by andrew-abimansour** [comment]
Conclusion is: install MDA from conda-forge and not pypi.
